name: vivah
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter

  flutter_rating_bar: ^4.0.1
  google_fonts: ^3.0.1
  provider: ^6.0.3
  video_player: ^2.4.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/vivahblack.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
